// languages.js - 20 Language Support for Codegent

const LANGUAGES = {
  tr: {
    code: 'tr',
    name: 'Türkçe',
    flag: '🇹🇷',
    strings: {
      appName: 'Codegent',
      chat: 'Sohbet',
      files: 'Dosyalar',
      editor: 'Editör',
      preview: 'Önizleme',
      settings: 'Ayarlar',
      deploy: 'Yayınla',
      newFile: 'Yeni Dosya',
      newProject: 'Yeni Proje',
      openProject: 'Proje Aç',
      saveProject: 'Projeyi Kaydet',
      deleteProject: 'Projeyi Sil',
      send: 'Gönder',
      typeMessage: 'Mesajınızı yazın...',
      selectModel: 'Model Seç',
      compare: 'Karşılaştır',
      regenerate: 'Yeniden Oluştur',
      tryWithAnotherModel: 'Başka modelle dene',
      imageGallery: 'Resim Galerisi',
      login: 'Giriş Yap',
      logout: 'Çıkış Yap',
      welcome: 'Hoş geldiniz!',
      askAnything: 'Bana bir şey sorun...',
      generating: 'Üretiliyor...',
      error: 'Hata',
      success: 'Başarılı',
      copy: 'Kopyala',
      copied: 'Kopyalandı!',
      download: 'İndir',
      delete: 'Sil',
      cancel: 'İptal',
      confirm: 'Onayla',
      close: 'Kapat',
      darkMode: 'Karanlık Mod',
      lightMode: 'Aydınlık Mod',
      language: 'Dil',
      customModel: 'Özel Model',
      addModel: 'Model Ekle',
      removeModel: 'Model Kaldır',
      templates: 'Şablonlar',
      noProjects: 'Henüz proje yok',
      noChats: 'Henüz sohbet yok',
      projectName: 'Proje Adı',
      fileName: 'Dosya Adı',
      deploySuccess: 'Proje başarıyla yayınlandı!',
      deployError: 'Yayınlama hatası',
      siteUrl: 'Site URL',
      mcpTools: 'MCP Araçları'
    }
  },
  en: {
    code: 'en',
    name: 'English',
    flag: '🇺🇸',
    strings: {
      appName: 'Codegent',
      chat: 'Chat',
      files: 'Files',
      editor: 'Editor',
      preview: 'Preview',
      settings: 'Settings',
      deploy: 'Deploy',
      newFile: 'New File',
      newProject: 'New Project',
      openProject: 'Open Project',
      saveProject: 'Save Project',
      deleteProject: 'Delete Project',
      send: 'Send',
      typeMessage: 'Type your message...',
      selectModel: 'Select Model',
      compare: 'Compare',
      regenerate: 'Regenerate',
      tryWithAnotherModel: 'Try with another model',
      imageGallery: 'Image Gallery',
      login: 'Login',
      logout: 'Logout',
      welcome: 'Welcome!',
      askAnything: 'Ask me anything...',
      generating: 'Generating...',
      error: 'Error',
      success: 'Success',
      copy: 'Copy',
      copied: 'Copied!',
      download: 'Download',
      delete: 'Delete',
      cancel: 'Cancel',
      confirm: 'Confirm',
      close: 'Close',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      language: 'Language',
      customModel: 'Custom Model',
      addModel: 'Add Model',
      removeModel: 'Remove Model',
      templates: 'Templates',
      noProjects: 'No projects yet',
      noChats: 'No chats yet',
      projectName: 'Project Name',
      fileName: 'File Name',
      deploySuccess: 'Project deployed successfully!',
      deployError: 'Deploy error',
      siteUrl: 'Site URL',
      mcpTools: 'MCP Tools'
    }
  },
  zh: {
    code: 'zh',
    name: '中文',
    flag: '🇨🇳',
    strings: {
      appName: 'Codegent',
      chat: '聊天',
      files: '文件',
      editor: '编辑器',
      preview: '预览',
      settings: '设置',
      deploy: '部署',
      newFile: '新文件',
      newProject: '新项目',
      openProject: '打开项目',
      saveProject: '保存项目',
      deleteProject: '删除项目',
      send: '发送',
      typeMessage: '输入消息...',
      selectModel: '选择模型',
      compare: '比较',
      regenerate: '重新生成',
      tryWithAnotherModel: '尝试其他模型',
      imageGallery: '图片库',
      login: '登录',
      logout: '退出',
      welcome: '欢迎！',
      askAnything: '问我任何问题...',
      generating: '生成中...',
      error: '错误',
      success: '成功',
      copy: '复制',
      copied: '已复制！',
      download: '下载',
      delete: '删除',
      cancel: '取消',
      confirm: '确认',
      close: '关闭',
      darkMode: '深色模式',
      lightMode: '浅色模式',
      language: '语言',
      customModel: '自定义模型',
      addModel: '添加模型',
      removeModel: '移除模型',
      templates: '模板',
      noProjects: '暂无项目',
      noChats: '暂无聊天',
      projectName: '项目名称',
      fileName: '文件名',
      deploySuccess: '项目部署成功！',
      deployError: '部署错误',
      siteUrl: '网站链接',
      mcpTools: 'MCP工具'
    }
  },
  es: {
    code: 'es',
    name: 'Español',
    flag: '🇪🇸',
    strings: {
      appName: 'Codegent',
      chat: 'Chat',
      files: 'Archivos',
      editor: 'Editor',
      preview: 'Vista previa',
      settings: 'Configuración',
      deploy: 'Desplegar',
      newFile: 'Nuevo Archivo',
      newProject: 'Nuevo Proyecto',
      openProject: 'Abrir Proyecto',
      saveProject: 'Guardar Proyecto',
      deleteProject: 'Eliminar Proyecto',
      send: 'Enviar',
      typeMessage: 'Escribe tu mensaje...',
      selectModel: 'Seleccionar Modelo',
      compare: 'Comparar',
      regenerate: 'Regenerar',
      tryWithAnotherModel: 'Probar con otro modelo',
      imageGallery: 'Galería de Imágenes',
      login: 'Iniciar sesión',
      logout: 'Cerrar sesión',
      welcome: '¡Bienvenido!',
      askAnything: 'Pregúntame cualquier cosa...',
      generating: 'Generando...',
      error: 'Error',
      success: 'Éxito',
      copy: 'Copiar',
      copied: '¡Copiado!',
      download: 'Descargar',
      delete: 'Eliminar',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      close: 'Cerrar',
      darkMode: 'Modo Oscuro',
      lightMode: 'Modo Claro',
      language: 'Idioma',
      customModel: 'Modelo Personalizado',
      addModel: 'Agregar Modelo',
      removeModel: 'Eliminar Modelo',
      templates: 'Plantillas',
      noProjects: 'Sin proyectos todavía',
      noChats: 'Sin chats todavía',
      projectName: 'Nombre del Proyecto',
      fileName: 'Nombre del Archivo',
      deploySuccess: '¡Proyecto desplegado exitosamente!',
      deployError: 'Error de despliegue',
      siteUrl: 'URL del Sitio',
      mcpTools: 'Herramientas MCP'
    }
  },
  ar: {
    code: 'ar',
    name: 'العربية',
    flag: '🇸🇦',
    rtl: true,
    strings: {
      appName: 'Codegent',
      chat: 'محادثة',
      files: 'ملفات',
      editor: 'محرر',
      preview: 'معاينة',
      settings: 'إعدادات',
      deploy: 'نشر',
      newFile: 'ملف جديد',
      newProject: 'مشروع جديد',
      openProject: 'فتح مشروع',
      saveProject: 'حفظ المشروع',
      deleteProject: 'حذف المشروع',
      send: 'إرسال',
      typeMessage: 'اكتب رسالتك...',
      selectModel: 'اختر النموذج',
      compare: 'مقارنة',
      regenerate: 'إعادة التوليد',
      tryWithAnotherModel: 'جرب مع نموذج آخر',
      imageGallery: 'معرض الصور',
      login: 'تسجيل الدخول',
      logout: 'تسجيل الخروج',
      welcome: 'مرحباً!',
      askAnything: 'اسألني أي شيء...',
      generating: 'جارٍ التوليد...',
      error: 'خطأ',
      success: 'نجاح',
      copy: 'نسخ',
      copied: 'تم النسخ!',
      download: 'تنزيل',
      delete: 'حذف',
      cancel: 'إلغاء',
      confirm: 'تأكيد',
      close: 'إغلاق',
      darkMode: 'الوضع الداكن',
      lightMode: 'الوضع الفاتح',
      language: 'اللغة',
      customModel: 'نموذج مخصص',
      addModel: 'إضافة نموذج',
      removeModel: 'إزالة نموذج',
      templates: 'قوالب',
      noProjects: 'لا توجد مشاريع بعد',
      noChats: 'لا توجد محادثات بعد',
      projectName: 'اسم المشروع',
      fileName: 'اسم الملف',
      deploySuccess: 'تم نشر المشروع بنجاح!',
      deployError: 'خطأ في النشر',
      siteUrl: 'رابط الموقع',
      mcpTools: 'أدوات MCP'
    }
  },
  hi: {
    code: 'hi',
    name: 'हिन्दी',
    flag: '🇮🇳',
    strings: {
      appName: 'Codegent',
      chat: 'चैट',
      files: 'फ़ाइलें',
      editor: 'संपादक',
      preview: 'पूर्वावलोकन',
      settings: 'सेटिंग्स',
      deploy: 'डिप्लॉय',
      newFile: 'नई फ़ाइल',
      newProject: 'नया प्रोजेक्ट',
      openProject: 'प्रोजेक्ट खोलें',
      saveProject: 'प्रोजेक्ट सहेजें',
      deleteProject: 'प्रोजेक्ट हटाएं',
      send: 'भेजें',
      typeMessage: 'अपना संदेश लिखें...',
      selectModel: 'मॉडल चुनें',
      compare: 'तुलना करें',
      regenerate: 'पुन: उत्पन्न करें',
      tryWithAnotherModel: 'दूसरे मॉडल से प्रयास करें',
      imageGallery: 'छवि गैलरी',
      login: 'लॉग इन',
      logout: 'लॉग आउट',
      welcome: 'स्वागत है!',
      askAnything: 'मुझसे कुछ भी पूछें...',
      generating: 'उत्पन्न हो रहा है...',
      error: 'त्रुटि',
      success: 'सफलता',
      copy: 'कॉपी',
      copied: 'कॉपी हो गया!',
      download: 'डाउनलोड',
      delete: 'हटाएं',
      cancel: 'रद्द करें',
      confirm: 'पुष्टि करें',
      close: 'बंद करें',
      darkMode: 'डार्क मोड',
      lightMode: 'लाइट मोड',
      language: 'भाषा',
      customModel: 'कस्टम मॉडल',
      addModel: 'मॉडल जोड़ें',
      removeModel: 'मॉडल हटाएं',
      templates: 'टेम्पलेट्स',
      noProjects: 'अभी तक कोई प्रोजेक्ट नहीं',
      noChats: 'अभी तक कोई चैट नहीं',
      projectName: 'प्रोजेक्ट का नाम',
      fileName: 'फ़ाइल का नाम',
      deploySuccess: 'प्रोजेक्ट सफलतापूर्वक डिप्लॉय हुआ!',
      deployError: 'डिप्लॉय त्रुटि',
      siteUrl: 'साइट URL',
      mcpTools: 'MCP टूल्स'
    }
  },
  pt: {
    code: 'pt',
    name: 'Português',
    flag: '🇧🇷',
    strings: {
      appName: 'Codegent',
      chat: 'Chat',
      files: 'Arquivos',
      editor: 'Editor',
      preview: 'Prévia',
      settings: 'Configurações',
      deploy: 'Implantar',
      newFile: 'Novo Arquivo',
      newProject: 'Novo Projeto',
      openProject: 'Abrir Projeto',
      saveProject: 'Salvar Projeto',
      deleteProject: 'Excluir Projeto',
      send: 'Enviar',
      typeMessage: 'Digite sua mensagem...',
      selectModel: 'Selecionar Modelo',
      compare: 'Comparar',
      regenerate: 'Regenerar',
      tryWithAnotherModel: 'Tente com outro modelo',
      imageGallery: 'Galeria de Imagens',
      login: 'Entrar',
      logout: 'Sair',
      welcome: 'Bem-vindo!',
      askAnything: 'Pergunte-me qualquer coisa...',
      generating: 'Gerando...',
      error: 'Erro',
      success: 'Sucesso',
      copy: 'Copiar',
      copied: 'Copiado!',
      download: 'Baixar',
      delete: 'Excluir',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      close: 'Fechar',
      darkMode: 'Modo Escuro',
      lightMode: 'Modo Claro',
      language: 'Idioma',
      customModel: 'Modelo Personalizado',
      addModel: 'Adicionar Modelo',
      removeModel: 'Remover Modelo',
      templates: 'Modelos',
      noProjects: 'Nenhum projeto ainda',
      noChats: 'Nenhum chat ainda',
      projectName: 'Nome do Projeto',
      fileName: 'Nome do Arquivo',
      deploySuccess: 'Projeto implantado com sucesso!',
      deployError: 'Erro de implantação',
      siteUrl: 'URL do Site',
      mcpTools: 'Ferramentas MCP'
    }
  },
  ru: {
    code: 'ru',
    name: 'Русский',
    flag: '🇷🇺',
    strings: {
      appName: 'Codegent',
      chat: 'Чат',
      files: 'Файлы',
      editor: 'Редактор',
      preview: 'Предпросмотр',
      settings: 'Настройки',
      deploy: 'Развернуть',
      newFile: 'Новый файл',
      newProject: 'Новый проект',
      openProject: 'Открыть проект',
      saveProject: 'Сохранить проект',
      deleteProject: 'Удалить проект',
      send: 'Отправить',
      typeMessage: 'Введите сообщение...',
      selectModel: 'Выбрать модель',
      compare: 'Сравнить',
      regenerate: 'Перегенерировать',
      tryWithAnotherModel: 'Попробовать с другой моделью',
      imageGallery: 'Галерея изображений',
      login: 'Войти',
      logout: 'Выйти',
      welcome: 'Добро пожаловать!',
      askAnything: 'Спросите меня о чём угодно...',
      generating: 'Генерация...',
      error: 'Ошибка',
      success: 'Успех',
      copy: 'Копировать',
      copied: 'Скопировано!',
      download: 'Скачать',
      delete: 'Удалить',
      cancel: 'Отмена',
      confirm: 'Подтвердить',
      close: 'Закрыть',
      darkMode: 'Тёмная тема',
      lightMode: 'Светлая тема',
      language: 'Язык',
      customModel: 'Своя модель',
      addModel: 'Добавить модель',
      removeModel: 'Удалить модель',
      templates: 'Шаблоны',
      noProjects: 'Пока нет проектов',
      noChats: 'Пока нет чатов',
      projectName: 'Название проекта',
      fileName: 'Имя файла',
      deploySuccess: 'Проект успешно развёрнут!',
      deployError: 'Ошибка развёртывания',
      siteUrl: 'URL сайта',
      mcpTools: 'Инструменты MCP'
    }
  },
  ja: {
    code: 'ja',
    name: '日本語',
    flag: '🇯🇵',
    strings: {
      appName: 'Codegent',
      chat: 'チャット',
      files: 'ファイル',
      editor: 'エディタ',
      preview: 'プレビュー',
      settings: '設定',
      deploy: 'デプロイ',
      newFile: '新規ファイル',
      newProject: '新規プロジェクト',
      openProject: 'プロジェクトを開く',
      saveProject: 'プロジェクトを保存',
      deleteProject: 'プロジェクトを削除',
      send: '送信',
      typeMessage: 'メッセージを入力...',
      selectModel: 'モデルを選択',
      compare: '比較',
      regenerate: '再生成',
      tryWithAnotherModel: '別のモデルで試す',
      imageGallery: '画像ギャラリー',
      login: 'ログイン',
      logout: 'ログアウト',
      welcome: 'ようこそ！',
      askAnything: '何でも聞いてください...',
      generating: '生成中...',
      error: 'エラー',
      success: '成功',
      copy: 'コピー',
      copied: 'コピーしました！',
      download: 'ダウンロード',
      delete: '削除',
      cancel: 'キャンセル',
      confirm: '確認',
      close: '閉じる',
      darkMode: 'ダークモード',
      lightMode: 'ライトモード',
      language: '言語',
      customModel: 'カスタムモデル',
      addModel: 'モデルを追加',
      removeModel: 'モデルを削除',
      templates: 'テンプレート',
      noProjects: 'プロジェクトがありません',
      noChats: 'チャットがありません',
      projectName: 'プロジェクト名',
      fileName: 'ファイル名',
      deploySuccess: 'プロジェクトのデプロイに成功しました！',
      deployError: 'デプロイエラー',
      siteUrl: 'サイトURL',
      mcpTools: 'MCPツール'
    }
  },
  de: {
    code: 'de',
    name: 'Deutsch',
    flag: '🇩🇪',
    strings: {
      appName: 'Codegent',
      chat: 'Chat',
      files: 'Dateien',
      editor: 'Editor',
      preview: 'Vorschau',
      settings: 'Einstellungen',
      deploy: 'Bereitstellen',
      newFile: 'Neue Datei',
      newProject: 'Neues Projekt',
      openProject: 'Projekt öffnen',
      saveProject: 'Projekt speichern',
      deleteProject: 'Projekt löschen',
      send: 'Senden',
      typeMessage: 'Nachricht eingeben...',
      selectModel: 'Modell auswählen',
      compare: 'Vergleichen',
      regenerate: 'Neu generieren',
      tryWithAnotherModel: 'Mit anderem Modell versuchen',
      imageGallery: 'Bildgalerie',
      login: 'Anmelden',
      logout: 'Abmelden',
      welcome: 'Willkommen!',
      askAnything: 'Fragen Sie mich etwas...',
      generating: 'Generiere...',
      error: 'Fehler',
      success: 'Erfolg',
      copy: 'Kopieren',
      copied: 'Kopiert!',
      download: 'Herunterladen',
      delete: 'Löschen',
      cancel: 'Abbrechen',
      confirm: 'Bestätigen',
      close: 'Schließen',
      darkMode: 'Dunkler Modus',
      lightMode: 'Heller Modus',
      language: 'Sprache',
      customModel: 'Benutzerdefiniertes Modell',
      addModel: 'Modell hinzufügen',
      removeModel: 'Modell entfernen',
      templates: 'Vorlagen',
      noProjects: 'Noch keine Projekte',
      noChats: 'Noch keine Chats',
      projectName: 'Projektname',
      fileName: 'Dateiname',
      deploySuccess: 'Projekt erfolgreich bereitgestellt!',
      deployError: 'Bereitstellungsfehler',
      siteUrl: 'Website-URL',
      mcpTools: 'MCP-Tools'
    }
  },
  fr: {
    code: 'fr',
    name: 'Français',
    flag: '🇫🇷',
    strings: {
      appName: 'Codegent',
      chat: 'Chat',
      files: 'Fichiers',
      editor: 'Éditeur',
      preview: 'Aperçu',
      settings: 'Paramètres',
      deploy: 'Déployer',
      newFile: 'Nouveau Fichier',
      newProject: 'Nouveau Projet',
      openProject: 'Ouvrir Projet',
      saveProject: 'Enregistrer Projet',
      deleteProject: 'Supprimer Projet',
      send: 'Envoyer',
      typeMessage: 'Tapez votre message...',
      selectModel: 'Sélectionner Modèle',
      compare: 'Comparer',
      regenerate: 'Régénérer',
      tryWithAnotherModel: 'Essayer avec un autre modèle',
      imageGallery: 'Galerie d\'Images',
      login: 'Connexion',
      logout: 'Déconnexion',
      welcome: 'Bienvenue!',
      askAnything: 'Posez-moi une question...',
      generating: 'Génération...',
      error: 'Erreur',
      success: 'Succès',
      copy: 'Copier',
      copied: 'Copié!',
      download: 'Télécharger',
      delete: 'Supprimer',
      cancel: 'Annuler',
      confirm: 'Confirmer',
      close: 'Fermer',
      darkMode: 'Mode Sombre',
      lightMode: 'Mode Clair',
      language: 'Langue',
      customModel: 'Modèle Personnalisé',
      addModel: 'Ajouter Modèle',
      removeModel: 'Supprimer Modèle',
      templates: 'Modèles',
      noProjects: 'Pas de projets encore',
      noChats: 'Pas de chats encore',
      projectName: 'Nom du Projet',
      fileName: 'Nom du Fichier',
      deploySuccess: 'Projet déployé avec succès!',
      deployError: 'Erreur de déploiement',
      siteUrl: 'URL du Site',
      mcpTools: 'Outils MCP'
    }
  },
  ko: {
    code: 'ko',
    name: '한국어',
    flag: '🇰🇷',
    strings: {
      appName: 'Codegent',
      chat: '채팅',
      files: '파일',
      editor: '편집기',
      preview: '미리보기',
      settings: '설정',
      deploy: '배포',
      newFile: '새 파일',
      newProject: '새 프로젝트',
      openProject: '프로젝트 열기',
      saveProject: '프로젝트 저장',
      deleteProject: '프로젝트 삭제',
      send: '보내기',
      typeMessage: '메시지를 입력하세요...',
      selectModel: '모델 선택',
      compare: '비교',
      regenerate: '다시 생성',
      tryWithAnotherModel: '다른 모델로 시도',
      imageGallery: '이미지 갤러리',
      login: '로그인',
      logout: '로그아웃',
      welcome: '환영합니다!',
      askAnything: '무엇이든 물어보세요...',
      generating: '생성 중...',
      error: '오류',
      success: '성공',
      copy: '복사',
      copied: '복사됨!',
      download: '다운로드',
      delete: '삭제',
      cancel: '취소',
      confirm: '확인',
      close: '닫기',
      darkMode: '다크 모드',
      lightMode: '라이트 모드',
      language: '언어',
      customModel: '사용자 정의 모델',
      addModel: '모델 추가',
      removeModel: '모델 제거',
      templates: '템플릿',
      noProjects: '프로젝트가 없습니다',
      noChats: '채팅이 없습니다',
      projectName: '프로젝트 이름',
      fileName: '파일 이름',
      deploySuccess: '프로젝트가 성공적으로 배포되었습니다!',
      deployError: '배포 오류',
      siteUrl: '사이트 URL',
      mcpTools: 'MCP 도구'
    }
  },
  it: {
    code: 'it',
    name: 'Italiano',
    flag: '🇮🇹',
    strings: {
      appName: 'Codegent',
      chat: 'Chat',
      files: 'File',
      editor: 'Editor',
      preview: 'Anteprima',
      settings: 'Impostazioni',
      deploy: 'Distribuisci',
      newFile: 'Nuovo File',
      newProject: 'Nuovo Progetto',
      openProject: 'Apri Progetto',
      saveProject: 'Salva Progetto',
      deleteProject: 'Elimina Progetto',
      send: 'Invia',
      typeMessage: 'Scrivi il tuo messaggio...',
      selectModel: 'Seleziona Modello',
      compare: 'Confronta',
      regenerate: 'Rigenera',
      tryWithAnotherModel: 'Prova con un altro modello',
      imageGallery: 'Galleria Immagini',
      login: 'Accedi',
      logout: 'Esci',
      welcome: 'Benvenuto!',
      askAnything: 'Chiedimi qualsiasi cosa...',
      generating: 'Generazione...',
      error: 'Errore',
      success: 'Successo',
      copy: 'Copia',
      copied: 'Copiato!',
      download: 'Scarica',
      delete: 'Elimina',
      cancel: 'Annulla',
      confirm: 'Conferma',
      close: 'Chiudi',
      darkMode: 'Modalità Scura',
      lightMode: 'Modalità Chiara',
      language: 'Lingua',
      customModel: 'Modello Personalizzato',
      addModel: 'Aggiungi Modello',
      removeModel: 'Rimuovi Modello',
      templates: 'Modelli',
      noProjects: 'Nessun progetto ancora',
      noChats: 'Nessun chat ancora',
      projectName: 'Nome Progetto',
      fileName: 'Nome File',
      deploySuccess: 'Progetto distribuito con successo!',
      deployError: 'Errore di distribuzione',
      siteUrl: 'URL del Sito',
      mcpTools: 'Strumenti MCP'
    }
  },
  vi: {
    code: 'vi',
    name: 'Tiếng Việt',
    flag: '🇻🇳',
    strings: {
      appName: 'Codegent',
      chat: 'Trò chuyện',
      files: 'Tệp',
      editor: 'Trình soạn thảo',
      preview: 'Xem trước',
      settings: 'Cài đặt',
      deploy: 'Triển khai',
      newFile: 'Tệp mới',
      newProject: 'Dự án mới',
      openProject: 'Mở dự án',
      saveProject: 'Lưu dự án',
      deleteProject: 'Xóa dự án',
      send: 'Gửi',
      typeMessage: 'Nhập tin nhắn...',
      selectModel: 'Chọn mô hình',
      compare: 'So sánh',
      regenerate: 'Tạo lại',
      tryWithAnotherModel: 'Thử với mô hình khác',
      imageGallery: 'Thư viện ảnh',
      login: 'Đăng nhập',
      logout: 'Đăng xuất',
      welcome: 'Chào mừng!',
      askAnything: 'Hỏi tôi bất cứ điều gì...',
      generating: 'Đang tạo...',
      error: 'Lỗi',
      success: 'Thành công',
      copy: 'Sao chép',
      copied: 'Đã sao chép!',
      download: 'Tải xuống',
      delete: 'Xóa',
      cancel: 'Hủy',
      confirm: 'Xác nhận',
      close: 'Đóng',
      darkMode: 'Chế độ tối',
      lightMode: 'Chế độ sáng',
      language: 'Ngôn ngữ',
      customModel: 'Mô hình tùy chỉnh',
      addModel: 'Thêm mô hình',
      removeModel: 'Xóa mô hình',
      templates: 'Mẫu',
      noProjects: 'Chưa có dự án',
      noChats: 'Chưa có trò chuyện',
      projectName: 'Tên dự án',
      fileName: 'Tên tệp',
      deploySuccess: 'Dự án đã được triển khai thành công!',
      deployError: 'Lỗi triển khai',
      siteUrl: 'URL trang web',
      mcpTools: 'Công cụ MCP'
    }
  },
  fa: {
    code: 'fa',
    name: 'فارسی',
    flag: '🇮🇷',
    rtl: true,
    strings: {
      appName: 'Codegent',
      chat: 'گفتگو',
      files: 'فایل‌ها',
      editor: 'ویرایشگر',
      preview: 'پیش‌نمایش',
      settings: 'تنظیمات',
      deploy: 'استقرار',
      newFile: 'فایل جدید',
      newProject: 'پروژه جدید',
      openProject: 'باز کردن پروژه',
      saveProject: 'ذخیره پروژه',
      deleteProject: 'حذف پروژه',
      send: 'ارسال',
      typeMessage: 'پیام خود را بنویسید...',
      selectModel: 'انتخاب مدل',
      compare: 'مقایسه',
      regenerate: 'بازتولید',
      tryWithAnotherModel: 'با مدل دیگر امتحان کنید',
      imageGallery: 'گالری تصاویر',
      login: 'ورود',
      logout: 'خروج',
      welcome: 'خوش آمدید!',
      askAnything: 'هر چیزی بپرسید...',
      generating: 'در حال تولید...',
      error: 'خطا',
      success: 'موفقیت',
      copy: 'کپی',
      copied: 'کپی شد!',
      download: 'دانلود',
      delete: 'حذف',
      cancel: 'انصراف',
      confirm: 'تأیید',
      close: 'بستن',
      darkMode: 'حالت تاریک',
      lightMode: 'حالت روشن',
      language: 'زبان',
      customModel: 'مدل سفارشی',
      addModel: 'افزودن مدل',
      removeModel: 'حذف مدل',
      templates: 'قالب‌ها',
      noProjects: 'هنوز پروژه‌ای نیست',
      noChats: 'هنوز گفتگویی نیست',
      projectName: 'نام پروژه',
      fileName: 'نام فایل',
      deploySuccess: 'پروژه با موفقیت مستقر شد!',
      deployError: 'خطای استقرار',
      siteUrl: 'آدرس سایت',
      mcpTools: 'ابزارهای MCP'
    }
  },
  pl: {
    code: 'pl',
    name: 'Polski',
    flag: '🇵🇱',
    strings: {
      appName: 'Codegent',
      chat: 'Czat',
      files: 'Pliki',
      editor: 'Edytor',
      preview: 'Podgląd',
      settings: 'Ustawienia',
      deploy: 'Wdrażaj',
      newFile: 'Nowy Plik',
      newProject: 'Nowy Projekt',
      openProject: 'Otwórz Projekt',
      saveProject: 'Zapisz Projekt',
      deleteProject: 'Usuń Projekt',
      send: 'Wyślij',
      typeMessage: 'Wpisz wiadomość...',
      selectModel: 'Wybierz Model',
      compare: 'Porównaj',
      regenerate: 'Regeneruj',
      tryWithAnotherModel: 'Spróbuj z innym modelem',
      imageGallery: 'Galeria Obrazów',
      login: 'Zaloguj się',
      logout: 'Wyloguj się',
      welcome: 'Witaj!',
      askAnything: 'Zapytaj o cokolwiek...',
      generating: 'Generowanie...',
      error: 'Błąd',
      success: 'Sukces',
      copy: 'Kopiuj',
      copied: 'Skopiowano!',
      download: 'Pobierz',
      delete: 'Usuń',
      cancel: 'Anuluj',
      confirm: 'Potwierdź',
      close: 'Zamknij',
      darkMode: 'Tryb Ciemny',
      lightMode: 'Tryb Jasny',
      language: 'Język',
      customModel: 'Model Niestandardowy',
      addModel: 'Dodaj Model',
      removeModel: 'Usuń Model',
      templates: 'Szablony',
      noProjects: 'Brak projektów',
      noChats: 'Brak czatów',
      projectName: 'Nazwa Projektu',
      fileName: 'Nazwa Pliku',
      deploySuccess: 'Projekt wdrożony pomyślnie!',
      deployError: 'Błąd wdrażania',
      siteUrl: 'URL Strony',
      mcpTools: 'Narzędzia MCP'
    }
  },
  uk: {
    code: 'uk',
    name: 'Українська',
    flag: '🇺🇦',
    strings: {
      appName: 'Codegent',
      chat: 'Чат',
      files: 'Файли',
      editor: 'Редактор',
      preview: 'Попередній перегляд',
      settings: 'Налаштування',
      deploy: 'Розгорнути',
      newFile: 'Новий файл',
      newProject: 'Новий проект',
      openProject: 'Відкрити проект',
      saveProject: 'Зберегти проект',
      deleteProject: 'Видалити проект',
      send: 'Надіслати',
      typeMessage: 'Введіть повідомлення...',
      selectModel: 'Вибрати модель',
      compare: 'Порівняти',
      regenerate: 'Перегенерувати',
      tryWithAnotherModel: 'Спробувати з іншою моделлю',
      imageGallery: 'Галерея зображень',
      login: 'Увійти',
      logout: 'Вийти',
      welcome: 'Ласкаво просимо!',
      askAnything: 'Запитайте що завгодно...',
      generating: 'Генерація...',
      error: 'Помилка',
      success: 'Успіх',
      copy: 'Копіювати',
      copied: 'Скопійовано!',
      download: 'Завантажити',
      delete: 'Видалити',
      cancel: 'Скасувати',
      confirm: 'Підтвердити',
      close: 'Закрити',
      darkMode: 'Темна тема',
      lightMode: 'Світла тема',
      language: 'Мова',
      customModel: 'Власна модель',
      addModel: 'Додати модель',
      removeModel: 'Видалити модель',
      templates: 'Шаблони',
      noProjects: 'Поки немає проектів',
      noChats: 'Поки немає чатів',
      projectName: 'Назва проекту',
      fileName: 'Ім\'я файлу',
      deploySuccess: 'Проект успішно розгорнуто!',
      deployError: 'Помилка розгортання',
      siteUrl: 'URL сайту',
      mcpTools: 'Інструменти MCP'
    }
  },
  ro: {
    code: 'ro',
    name: 'Română',
    flag: '🇷🇴',
    strings: {
      appName: 'Codegent',
      chat: 'Chat',
      files: 'Fișiere',
      editor: 'Editor',
      preview: 'Previzualizare',
      settings: 'Setări',
      deploy: 'Implementare',
      newFile: 'Fișier Nou',
      newProject: 'Proiect Nou',
      openProject: 'Deschide Proiect',
      saveProject: 'Salvează Proiect',
      deleteProject: 'Șterge Proiect',
      send: 'Trimite',
      typeMessage: 'Scrie mesajul...',
      selectModel: 'Selectează Model',
      compare: 'Compară',
      regenerate: 'Regenerează',
      tryWithAnotherModel: 'Încearcă cu alt model',
      imageGallery: 'Galerie Imagini',
      login: 'Autentificare',
      logout: 'Deconectare',
      welcome: 'Bun venit!',
      askAnything: 'Întreabă-mă orice...',
      generating: 'Generare...',
      error: 'Eroare',
      success: 'Succes',
      copy: 'Copiază',
      copied: 'Copiat!',
      download: 'Descarcă',
      delete: 'Șterge',
      cancel: 'Anulează',
      confirm: 'Confirmă',
      close: 'Închide',
      darkMode: 'Mod Întunecat',
      lightMode: 'Mod Luminos',
      language: 'Limbă',
      customModel: 'Model Personalizat',
      addModel: 'Adaugă Model',
      removeModel: 'Elimină Model',
      templates: 'Șabloane',
      noProjects: 'Niciun proiect încă',
      noChats: 'Niciun chat încă',
      projectName: 'Nume Proiect',
      fileName: 'Nume Fișier',
      deploySuccess: 'Proiect implementat cu succes!',
      deployError: 'Eroare de implementare',
      siteUrl: 'URL Site',
      mcpTools: 'Instrumente MCP'
    }
  },
  nl: {
    code: 'nl',
    name: 'Nederlands',
    flag: '🇳🇱',
    strings: {
      appName: 'Codegent',
      chat: 'Chat',
      files: 'Bestanden',
      editor: 'Editor',
      preview: 'Voorbeeld',
      settings: 'Instellingen',
      deploy: 'Implementeren',
      newFile: 'Nieuw Bestand',
      newProject: 'Nieuw Project',
      openProject: 'Project Openen',
      saveProject: 'Project Opslaan',
      deleteProject: 'Project Verwijderen',
      send: 'Verzenden',
      typeMessage: 'Typ je bericht...',
      selectModel: 'Model Selecteren',
      compare: 'Vergelijken',
      regenerate: 'Regenereren',
      tryWithAnotherModel: 'Probeer met ander model',
      imageGallery: 'Afbeeldingsgalerij',
      login: 'Inloggen',
      logout: 'Uitloggen',
      welcome: 'Welkom!',
      askAnything: 'Vraag me alles...',
      generating: 'Genereren...',
      error: 'Fout',
      success: 'Succes',
      copy: 'Kopiëren',
      copied: 'Gekopieerd!',
      download: 'Downloaden',
      delete: 'Verwijderen',
      cancel: 'Annuleren',
      confirm: 'Bevestigen',
      close: 'Sluiten',
      darkMode: 'Donkere Modus',
      lightMode: 'Lichte Modus',
      language: 'Taal',
      customModel: 'Aangepast Model',
      addModel: 'Model Toevoegen',
      removeModel: 'Model Verwijderen',
      templates: 'Sjablonen',
      noProjects: 'Nog geen projecten',
      noChats: 'Nog geen chats',
      projectName: 'Projectnaam',
      fileName: 'Bestandsnaam',
      deploySuccess: 'Project succesvol geïmplementeerd!',
      deployError: 'Implementatiefout',
      siteUrl: 'Website URL',
      mcpTools: 'MCP-tools'
    }
  },
  th: {
    code: 'th',
    name: 'ไทย',
    flag: '🇹🇭',
    strings: {
      appName: 'Codegent',
      chat: 'แชท',
      files: 'ไฟล์',
      editor: 'ตัวแก้ไข',
      preview: 'ดูตัวอย่าง',
      settings: 'การตั้งค่า',
      deploy: 'ปรับใช้',
      newFile: 'ไฟล์ใหม่',
      newProject: 'โปรเจกต์ใหม่',
      openProject: 'เปิดโปรเจกต์',
      saveProject: 'บันทึกโปรเจกต์',
      deleteProject: 'ลบโปรเจกต์',
      send: 'ส่ง',
      typeMessage: 'พิมพ์ข้อความ...',
      selectModel: 'เลือกโมเดล',
      compare: 'เปรียบเทียบ',
      regenerate: 'สร้างใหม่',
      tryWithAnotherModel: 'ลองกับโมเดลอื่น',
      imageGallery: 'แกลเลอรีรูปภาพ',
      login: 'เข้าสู่ระบบ',
      logout: 'ออกจากระบบ',
      welcome: 'ยินดีต้อนรับ!',
      askAnything: 'ถามอะไรก็ได้...',
      generating: 'กำลังสร้าง...',
      error: 'ข้อผิดพลาด',
      success: 'สำเร็จ',
      copy: 'คัดลอก',
      copied: 'คัดลอกแล้ว!',
      download: 'ดาวน์โหลด',
      delete: 'ลบ',
      cancel: 'ยกเลิก',
      confirm: 'ยืนยัน',
      close: 'ปิด',
      darkMode: 'โหมดมืด',
      lightMode: 'โหมดสว่าง',
      language: 'ภาษา',
      customModel: 'โมเดลกำหนดเอง',
      addModel: 'เพิ่มโมเดล',
      removeModel: 'ลบโมเดล',
      templates: 'เทมเพลต',
      noProjects: 'ยังไม่มีโปรเจกต์',
      noChats: 'ยังไม่มีแชท',
      projectName: 'ชื่อโปรเจกต์',
      fileName: 'ชื่อไฟล์',
      deploySuccess: 'ปรับใช้โปรเจกต์สำเร็จ!',
      deployError: 'ข้อผิดพลาดในการปรับใช้',
      siteUrl: 'URL เว็บไซต์',
      mcpTools: 'เครื่องมือ MCP'
    }
  }
};

// Language Manager
class LanguageManager {
  constructor() {
    this.currentLanguage = 'en';
    this.listeners = [];
  }

  init() {
    const saved = localStorage.getItem('codegent_language');
    if (saved && LANGUAGES[saved]) {
      this.currentLanguage = saved;
    } else {
      const browserLang = navigator.language.split('-')[0];
      if (LANGUAGES[browserLang]) {
        this.currentLanguage = browserLang;
      }
    }
    this.applyLanguage();
  }

  setLanguage(code) {
    if (LANGUAGES[code]) {
      this.currentLanguage = code;
      localStorage.setItem('codegent_language', code);
      this.applyLanguage();
      this.notifyListeners();
    }
  }

  getCurrentLanguage() {
    return LANGUAGES[this.currentLanguage];
  }

  getString(key) {
    const lang = LANGUAGES[this.currentLanguage];
    return lang?.strings?.[key] || LANGUAGES.en.strings[key] || key;
  }

  t(key) {
    return this.getString(key);
  }

  applyLanguage() {
    const lang = LANGUAGES[this.currentLanguage];
    document.documentElement.lang = lang.code;
    document.documentElement.dir = lang.rtl ? 'rtl' : 'ltr';
  }

  onLanguageChange(callback) {
    this.listeners.push(callback);
    return () => {
      this.listeners = this.listeners.filter(l => l !== callback);
    };
  }

  notifyListeners() {
    this.listeners.forEach(callback => callback(this.currentLanguage));
  }

  getAllLanguages() {
    return Object.values(LANGUAGES).map(lang => ({
      code: lang.code,
      name: lang.name,
      flag: lang.flag
    }));
  }
}

// Create global instance
const i18n = new LanguageManager();

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { LANGUAGES, LanguageManager, i18n };
}
