/**
 * Codegent - Multi-language Support
 * 20 languages with translations for all UI elements
 */

const LANGUAGES = {
  en: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'Welcome to Codegent',
      guestMode: 'Guest Mode',
      signIn: 'Sign In',
      signOut: 'Sign Out',
      newProject: 'New Project',
      openProject: 'Open Project',
      saveProject: 'Save Project',
      deploy: 'Deploy',
      deploying: 'Deploying...',
      deploySuccess: 'Deployed Successfully!',
      deployError: 'Deployment Failed',
      files: 'Files',
      preview: 'Preview',
      chat: 'Chat',
      settings: 'Settings',
      models: 'Models',
      selectModel: 'Select Model',
      compare: 'Compare Models',
      regenerate: 'Regenerate',
      send: 'Send',
      typeMessage: 'Type your message...',
      thinking: 'Thinking...',
      error: 'Error',
      retry: 'Retry',
      cancel: 'Cancel',
      confirm: 'Confirm',
      delete: 'Delete',
      rename: 'Rename',
      newFile: 'New File',
      newFolder: 'New Folder',
      loginRequired: 'This model requires login. Would you like to sign in?',
      cloudSyncOn: 'Cloud Sync: On',
      cloudSyncOff: 'Cloud Sync: Off',
      localStorage: 'Using Local Storage',
      noPreview: 'No preview available',
      runCode: 'Run Code',
      clearChat: 'Clear Chat',
      exportChat: 'Export Chat',
      importChat: 'Import Chat',
      language: 'Language',
      theme: 'Theme',
      dark: 'Dark',
      light: 'Light',
      auto: 'Auto'
    }
  },
  tr: {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'Codegent\'e Hoş Geldiniz',
      guestMode: 'Misafir Modu',
      signIn: 'Giriş Yap',
      signOut: 'Çıkış Yap',
      newProject: 'Yeni Proje',
      openProject: 'Proje Aç',
      saveProject: 'Projeyi Kaydet',
      deploy: 'Yayınla',
      deploying: 'Yayınlanıyor...',
      deploySuccess: 'Başarıyla Yayınlandı!',
      deployError: 'Yayınlama Başarısız',
      files: 'Dosyalar',
      preview: 'Önizleme',
      chat: 'Sohbet',
      settings: 'Ayarlar',
      models: 'Modeller',
      selectModel: 'Model Seç',
      compare: 'Modelleri Karşılaştır',
      regenerate: 'Yeniden Oluştur',
      send: 'Gönder',
      typeMessage: 'Mesajınızı yazın...',
      thinking: 'Düşünüyor...',
      error: 'Hata',
      retry: 'Tekrar Dene',
      cancel: 'İptal',
      confirm: 'Onayla',
      delete: 'Sil',
      rename: 'Yeniden Adlandır',
      newFile: 'Yeni Dosya',
      newFolder: 'Yeni Klasör',
      loginRequired: 'Bu model için giriş gerekli. Giriş yapmak ister misiniz?',
      cloudSyncOn: 'Bulut Senkronizasyonu: Açık',
      cloudSyncOff: 'Bulut Senkronizasyonu: Kapalı',
      localStorage: 'Yerel Depolama Kullanılıyor',
      noPreview: 'Önizleme mevcut değil',
      runCode: 'Kodu Çalıştır',
      clearChat: 'Sohbeti Temizle',
      exportChat: 'Sohbeti Dışa Aktar',
      importChat: 'Sohbeti İçe Aktar',
      language: 'Dil',
      theme: 'Tema',
      dark: 'Koyu',
      light: 'Açık',
      auto: 'Otomatik'
    }
  },
  es: {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'Bienvenido a Codegent',
      guestMode: 'Modo Invitado',
      signIn: 'Iniciar Sesión',
      signOut: 'Cerrar Sesión',
      newProject: 'Nuevo Proyecto',
      openProject: 'Abrir Proyecto',
      saveProject: 'Guardar Proyecto',
      deploy: 'Desplegar',
      deploying: 'Desplegando...',
      deploySuccess: '¡Desplegado Exitosamente!',
      deployError: 'Despliegue Fallido',
      files: 'Archivos',
      preview: 'Vista Previa',
      chat: 'Chat',
      settings: 'Configuración',
      models: 'Modelos',
      selectModel: 'Seleccionar Modelo',
      compare: 'Comparar Modelos',
      regenerate: 'Regenerar',
      send: 'Enviar',
      typeMessage: 'Escribe tu mensaje...',
      thinking: 'Pensando...',
      error: 'Error',
      retry: 'Reintentar',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      delete: 'Eliminar',
      rename: 'Renombrar',
      newFile: 'Nuevo Archivo',
      newFolder: 'Nueva Carpeta',
      loginRequired: 'Este modelo requiere inicio de sesión. ¿Desea iniciar sesión?',
      cloudSyncOn: 'Sincronización en la Nube: Activada',
      cloudSyncOff: 'Sincronización en la Nube: Desactivada',
      localStorage: 'Usando Almacenamiento Local',
      noPreview: 'Vista previa no disponible',
      runCode: 'Ejecutar Código',
      clearChat: 'Limpiar Chat',
      exportChat: 'Exportar Chat',
      importChat: 'Importar Chat',
      language: 'Idioma',
      theme: 'Tema',
      dark: 'Oscuro',
      light: 'Claro',
      auto: 'Automático'
    }
  },
  fr: {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'Bienvenue sur Codegent',
      guestMode: 'Mode Invité',
      signIn: 'Se Connecter',
      signOut: 'Se Déconnecter',
      newProject: 'Nouveau Projet',
      openProject: 'Ouvrir Projet',
      saveProject: 'Enregistrer Projet',
      deploy: 'Déployer',
      deploying: 'Déploiement...',
      deploySuccess: 'Déployé avec Succès!',
      deployError: 'Échec du Déploiement',
      files: 'Fichiers',
      preview: 'Aperçu',
      chat: 'Chat',
      settings: 'Paramètres',
      models: 'Modèles',
      selectModel: 'Sélectionner Modèle',
      compare: 'Comparer Modèles',
      regenerate: 'Régénérer',
      send: 'Envoyer',
      typeMessage: 'Tapez votre message...',
      thinking: 'Réflexion...',
      error: 'Erreur',
      retry: 'Réessayer',
      cancel: 'Annuler',
      confirm: 'Confirmer',
      delete: 'Supprimer',
      rename: 'Renommer',
      newFile: 'Nouveau Fichier',
      newFolder: 'Nouveau Dossier',
      loginRequired: 'Ce modèle nécessite une connexion. Voulez-vous vous connecter?',
      cloudSyncOn: 'Synchronisation Cloud: Activée',
      cloudSyncOff: 'Synchronisation Cloud: Désactivée',
      localStorage: 'Utilisation du Stockage Local',
      noPreview: 'Aperçu non disponible',
      runCode: 'Exécuter Code',
      clearChat: 'Effacer Chat',
      exportChat: 'Exporter Chat',
      importChat: 'Importer Chat',
      language: 'Langue',
      theme: 'Thème',
      dark: 'Sombre',
      light: 'Clair',
      auto: 'Automatique'
    }
  },
  de: {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'Willkommen bei Codegent',
      guestMode: 'Gastmodus',
      signIn: 'Anmelden',
      signOut: 'Abmelden',
      newProject: 'Neues Projekt',
      openProject: 'Projekt Öffnen',
      saveProject: 'Projekt Speichern',
      deploy: 'Bereitstellen',
      deploying: 'Bereitstellung...',
      deploySuccess: 'Erfolgreich Bereitgestellt!',
      deployError: 'Bereitstellung Fehlgeschlagen',
      files: 'Dateien',
      preview: 'Vorschau',
      chat: 'Chat',
      settings: 'Einstellungen',
      models: 'Modelle',
      selectModel: 'Modell Auswählen',
      compare: 'Modelle Vergleichen',
      regenerate: 'Regenerieren',
      send: 'Senden',
      typeMessage: 'Nachricht eingeben...',
      thinking: 'Denken...',
      error: 'Fehler',
      retry: 'Wiederholen',
      cancel: 'Abbrechen',
      confirm: 'Bestätigen',
      delete: 'Löschen',
      rename: 'Umbenennen',
      newFile: 'Neue Datei',
      newFolder: 'Neuer Ordner',
      loginRequired: 'Dieses Modell erfordert eine Anmeldung. Möchten Sie sich anmelden?',
      cloudSyncOn: 'Cloud-Sync: Ein',
      cloudSyncOff: 'Cloud-Sync: Aus',
      localStorage: 'Lokaler Speicher Wird Verwendet',
      noPreview: 'Vorschau nicht verfügbar',
      runCode: 'Code Ausführen',
      clearChat: 'Chat Löschen',
      exportChat: 'Chat Exportieren',
      importChat: 'Chat Importieren',
      language: 'Sprache',
      theme: 'Thema',
      dark: 'Dunkel',
      light: 'Hell',
      auto: 'Automatisch'
    }
  },
  it: {
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'Benvenuto su Codegent',
      guestMode: 'Modalità Ospite',
      signIn: 'Accedi',
      signOut: 'Esci',
      newProject: 'Nuovo Progetto',
      openProject: 'Apri Progetto',
      saveProject: 'Salva Progetto',
      deploy: 'Distribuisci',
      deploying: 'Distribuzione...',
      deploySuccess: 'Distribuito con Successo!',
      deployError: 'Distribuzione Fallita',
      files: 'File',
      preview: 'Anteprima',
      chat: 'Chat',
      settings: 'Impostazioni',
      models: 'Modelli',
      selectModel: 'Seleziona Modello',
      compare: 'Confronta Modelli',
      regenerate: 'Rigenera',
      send: 'Invia',
      typeMessage: 'Scrivi il tuo messaggio...',
      thinking: 'Pensando...',
      error: 'Errore',
      retry: 'Riprova',
      cancel: 'Annulla',
      confirm: 'Conferma',
      delete: 'Elimina',
      rename: 'Rinomina',
      newFile: 'Nuovo File',
      newFolder: 'Nuova Cartella',
      loginRequired: 'Questo modello richiede l\'accesso. Vuoi accedere?',
      cloudSyncOn: 'Sincronizzazione Cloud: Attiva',
      cloudSyncOff: 'Sincronizzazione Cloud: Disattiva',
      localStorage: 'Utilizzo Archivio Locale',
      noPreview: 'Anteprima non disponibile',
      runCode: 'Esegui Codice',
      clearChat: 'Cancella Chat',
      exportChat: 'Esporta Chat',
      importChat: 'Importa Chat',
      language: 'Lingua',
      theme: 'Tema',
      dark: 'Scuro',
      light: 'Chiaro',
      auto: 'Automatico'
    }
  },
  pt: {
    code: 'pt',
    name: 'Portuguese',
    nativeName: 'Português',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'Bem-vindo ao Codegent',
      guestMode: 'Modo Convidado',
      signIn: 'Entrar',
      signOut: 'Sair',
      newProject: 'Novo Projeto',
      openProject: 'Abrir Projeto',
      saveProject: 'Salvar Projeto',
      deploy: 'Implantar',
      deploying: 'Implantando...',
      deploySuccess: 'Implantado com Sucesso!',
      deployError: 'Implantação Falhou',
      files: 'Arquivos',
      preview: 'Prévia',
      chat: 'Chat',
      settings: 'Configurações',
      models: 'Modelos',
      selectModel: 'Selecionar Modelo',
      compare: 'Comparar Modelos',
      regenerate: 'Regenerar',
      send: 'Enviar',
      typeMessage: 'Digite sua mensagem...',
      thinking: 'Pensando...',
      error: 'Erro',
      retry: 'Tentar Novamente',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      delete: 'Excluir',
      rename: 'Renomear',
      newFile: 'Novo Arquivo',
      newFolder: 'Nova Pasta',
      loginRequired: 'Este modelo requer login. Deseja fazer login?',
      cloudSyncOn: 'Sincronização na Nuvem: Ativada',
      cloudSyncOff: 'Sincronização na Nuvem: Desativada',
      localStorage: 'Usando Armazenamento Local',
      noPreview: 'Prévia não disponível',
      runCode: 'Executar Código',
      clearChat: 'Limpar Chat',
      exportChat: 'Exportar Chat',
      importChat: 'Importar Chat',
      language: 'Idioma',
      theme: 'Tema',
      dark: 'Escuro',
      light: 'Claro',
      auto: 'Automático'
    }
  },
  ru: {
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'Добро пожаловать в Codegent',
      guestMode: 'Гостевой Режим',
      signIn: 'Войти',
      signOut: 'Выйти',
      newProject: 'Новый Проект',
      openProject: 'Открыть Проект',
      saveProject: 'Сохранить Проект',
      deploy: 'Развернуть',
      deploying: 'Развертывание...',
      deploySuccess: 'Успешно Развернуто!',
      deployError: 'Ошибка Развертывания',
      files: 'Файлы',
      preview: 'Предпросмотр',
      chat: 'Чат',
      settings: 'Настройки',
      models: 'Модели',
      selectModel: 'Выбрать Модель',
      compare: 'Сравнить Модели',
      regenerate: 'Регенерировать',
      send: 'Отправить',
      typeMessage: 'Введите сообщение...',
      thinking: 'Думаю...',
      error: 'Ошибка',
      retry: 'Повторить',
      cancel: 'Отмена',
      confirm: 'Подтвердить',
      delete: 'Удалить',
      rename: 'Переименовать',
      newFile: 'Новый Файл',
      newFolder: 'Новая Папка',
      loginRequired: 'Для этой модели требуется вход. Хотите войти?',
      cloudSyncOn: 'Облачная Синхронизация: Вкл',
      cloudSyncOff: 'Облачная Синхронизация: Выкл',
      localStorage: 'Используется Локальное Хранилище',
      noPreview: 'Предпросмотр недоступен',
      runCode: 'Запустить Код',
      clearChat: 'Очистить Чат',
      exportChat: 'Экспорт Чата',
      importChat: 'Импорт Чата',
      language: 'Язык',
      theme: 'Тема',
      dark: 'Темная',
      light: 'Светлая',
      auto: 'Авто'
    }
  },
  zh: {
    code: 'zh',
    name: 'Chinese',
    nativeName: '中文',
    translations: {
      appTitle: 'Codegent AI助手',
      welcome: '欢迎使用Codegent',
      guestMode: '访客模式',
      signIn: '登录',
      signOut: '退出',
      newProject: '新建项目',
      openProject: '打开项目',
      saveProject: '保存项目',
      deploy: '部署',
      deploying: '正在部署...',
      deploySuccess: '部署成功！',
      deployError: '部署失败',
      files: '文件',
      preview: '预览',
      chat: '聊天',
      settings: '设置',
      models: '模型',
      selectModel: '选择模型',
      compare: '比较模型',
      regenerate: '重新生成',
      send: '发送',
      typeMessage: '输入消息...',
      thinking: '思考中...',
      error: '错误',
      retry: '重试',
      cancel: '取消',
      confirm: '确认',
      delete: '删除',
      rename: '重命名',
      newFile: '新建文件',
      newFolder: '新建文件夹',
      loginRequired: '此模型需要登录。是否登录？',
      cloudSyncOn: '云同步：开启',
      cloudSyncOff: '云同步：关闭',
      localStorage: '使用本地存储',
      noPreview: '无法预览',
      runCode: '运行代码',
      clearChat: '清空聊天',
      exportChat: '导出聊天',
      importChat: '导入聊天',
      language: '语言',
      theme: '主题',
      dark: '深色',
      light: '浅色',
      auto: '自动'
    }
  },
  ja: {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    translations: {
      appTitle: 'Codegent AIエージェント',
      welcome: 'Codegentへようこそ',
      guestMode: 'ゲストモード',
      signIn: 'ログイン',
      signOut: 'ログアウト',
      newProject: '新規プロジェクト',
      openProject: 'プロジェクトを開く',
      saveProject: 'プロジェクトを保存',
      deploy: 'デプロイ',
      deploying: 'デプロイ中...',
      deploySuccess: 'デプロイ成功！',
      deployError: 'デプロイ失敗',
      files: 'ファイル',
      preview: 'プレビュー',
      chat: 'チャット',
      settings: '設定',
      models: 'モデル',
      selectModel: 'モデルを選択',
      compare: 'モデルを比較',
      regenerate: '再生成',
      send: '送信',
      typeMessage: 'メッセージを入力...',
      thinking: '考え中...',
      error: 'エラー',
      retry: '再試行',
      cancel: 'キャンセル',
      confirm: '確認',
      delete: '削除',
      rename: '名前変更',
      newFile: '新規ファイル',
      newFolder: '新規フォルダ',
      loginRequired: 'このモデルにはログインが必要です。ログインしますか？',
      cloudSyncOn: 'クラウド同期：オン',
      cloudSyncOff: 'クラウド同期：オフ',
      localStorage: 'ローカルストレージ使用中',
      noPreview: 'プレビュー不可',
      runCode: 'コード実行',
      clearChat: 'チャットをクリア',
      exportChat: 'チャットをエクスポート',
      importChat: 'チャットをインポート',
      language: '言語',
      theme: 'テーマ',
      dark: 'ダーク',
      light: 'ライト',
      auto: '自動'
    }
  },
  ko: {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    translations: {
      appTitle: 'Codegent AI 에이전트',
      welcome: 'Codegent에 오신 것을 환영합니다',
      guestMode: '게스트 모드',
      signIn: '로그인',
      signOut: '로그아웃',
      newProject: '새 프로젝트',
      openProject: '프로젝트 열기',
      saveProject: '프로젝트 저장',
      deploy: '배포',
      deploying: '배포 중...',
      deploySuccess: '배포 성공!',
      deployError: '배포 실패',
      files: '파일',
      preview: '미리보기',
      chat: '채팅',
      settings: '설정',
      models: '모델',
      selectModel: '모델 선택',
      compare: '모델 비교',
      regenerate: '재생성',
      send: '전송',
      typeMessage: '메시지를 입력하세요...',
      thinking: '생각 중...',
      error: '오류',
      retry: '재시도',
      cancel: '취소',
      confirm: '확인',
      delete: '삭제',
      rename: '이름 변경',
      newFile: '새 파일',
      newFolder: '새 폴더',
      loginRequired: '이 모델은 로그인이 필요합니다. 로그인하시겠습니까?',
      cloudSyncOn: '클라우드 동기화: 켜짐',
      cloudSyncOff: '클라우드 동기화: 꺼짐',
      localStorage: '로컬 스토리지 사용 중',
      noPreview: '미리보기 불가',
      runCode: '코드 실행',
      clearChat: '채팅 지우기',
      exportChat: '채팅 내보내기',
      importChat: '채팅 가져오기',
      language: '언어',
      theme: '테마',
      dark: '다크',
      light: '라이트',
      auto: '자동'
    }
  },
  ar: {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'مرحباً بك في Codegent',
      guestMode: 'وضع الضيف',
      signIn: 'تسجيل الدخول',
      signOut: 'تسجيل الخروج',
      newProject: 'مشروع جديد',
      openProject: 'فتح مشروع',
      saveProject: 'حفظ المشروع',
      deploy: 'نشر',
      deploying: 'جاري النشر...',
      deploySuccess: 'تم النشر بنجاح!',
      deployError: 'فشل النشر',
      files: 'الملفات',
      preview: 'معاينة',
      chat: 'محادثة',
      settings: 'الإعدادات',
      models: 'النماذج',
      selectModel: 'اختر النموذج',
      compare: 'مقارنة النماذج',
      regenerate: 'إعادة التوليد',
      send: 'إرسال',
      typeMessage: 'اكتب رسالتك...',
      thinking: 'جاري التفكير...',
      error: 'خطأ',
      retry: 'إعادة المحاولة',
      cancel: 'إلغاء',
      confirm: 'تأكيد',
      delete: 'حذف',
      rename: 'إعادة تسمية',
      newFile: 'ملف جديد',
      newFolder: 'مجلد جديد',
      loginRequired: 'هذا النموذج يتطلب تسجيل الدخول. هل تريد تسجيل الدخول؟',
      cloudSyncOn: 'المزامنة السحابية: مفعلة',
      cloudSyncOff: 'المزامنة السحابية: معطلة',
      localStorage: 'استخدام التخزين المحلي',
      noPreview: 'المعاينة غير متوفرة',
      runCode: 'تشغيل الكود',
      clearChat: 'مسح المحادثة',
      exportChat: 'تصدير المحادثة',
      importChat: 'استيراد المحادثة',
      language: 'اللغة',
      theme: 'السمة',
      dark: 'داكن',
      light: 'فاتح',
      auto: 'تلقائي'
    }
  },
  hi: {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिंदी',
    translations: {
      appTitle: 'Codegent AI एजेंट',
      welcome: 'Codegent में आपका स्वागत है',
      guestMode: 'अतिथि मोड',
      signIn: 'साइन इन करें',
      signOut: 'साइन आउट करें',
      newProject: 'नई परियोजना',
      openProject: 'परियोजना खोलें',
      saveProject: 'परियोजना सहेजें',
      deploy: 'डिप्लॉय करें',
      deploying: 'डिप्लॉय हो रहा है...',
      deploySuccess: 'सफलतापूर्वक डिप्लॉय हो गया!',
      deployError: 'डिप्लॉय विफल',
      files: 'फाइलें',
      preview: 'पूर्वावलोकन',
      chat: 'चैट',
      settings: 'सेटिंग्स',
      models: 'मॉडल',
      selectModel: 'मॉडल चुनें',
      compare: 'मॉडल तुलना करें',
      regenerate: 'पुनर्जनन',
      send: 'भेजें',
      typeMessage: 'अपना संदेश लिखें...',
      thinking: 'सोच रहा है...',
      error: 'त्रुटि',
      retry: 'पुनः प्रयास करें',
      cancel: 'रद्द करें',
      confirm: 'पुष्टि करें',
      delete: 'हटाएं',
      rename: 'नाम बदलें',
      newFile: 'नई फाइल',
      newFolder: 'नया फ़ोल्डर',
      loginRequired: 'इस मॉडल के लिए लॉगिन आवश्यक है। क्या आप लॉगिन करना चाहेंगे?',
      cloudSyncOn: 'क्लाउड सिंक: चालू',
      cloudSyncOff: 'क्लाउड सिंक: बंद',
      localStorage: 'स्थानीय संग्रहण उपयोग में',
      noPreview: 'पूर्वावलोकन उपलब्ध नहीं',
      runCode: 'कोड चलाएं',
      clearChat: 'चैट साफ़ करें',
      exportChat: 'चैट निर्यात करें',
      importChat: 'चैट आयात करें',
      language: 'भाषा',
      theme: 'थीम',
      dark: 'डार्क',
      light: 'लाइट',
      auto: 'स्वचालित'
    }
  },
  pl: {
    code: 'pl',
    name: 'Polish',
    nativeName: 'Polski',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'Witaj w Codegent',
      guestMode: 'Tryb Gościa',
      signIn: 'Zaloguj się',
      signOut: 'Wyloguj się',
      newProject: 'Nowy Projekt',
      openProject: 'Otwórz Projekt',
      saveProject: 'Zapisz Projekt',
      deploy: 'Wdróż',
      deploying: 'Wdrażanie...',
      deploySuccess: 'Wdrożono Pomyślnie!',
      deployError: 'Wdrożenie Nieudane',
      files: 'Pliki',
      preview: 'Podgląd',
      chat: 'Czat',
      settings: 'Ustawienia',
      models: 'Modele',
      selectModel: 'Wybierz Model',
      compare: 'Porównaj Modele',
      regenerate: 'Regeneruj',
      send: 'Wyślij',
      typeMessage: 'Wpisz wiadomość...',
      thinking: 'Myślenie...',
      error: 'Błąd',
      retry: 'Ponów',
      cancel: 'Anuluj',
      confirm: 'Potwierdź',
      delete: 'Usuń',
      rename: 'Zmień nazwę',
      newFile: 'Nowy Plik',
      newFolder: 'Nowy Folder',
      loginRequired: 'Ten model wymaga logowania. Czy chcesz się zalogować?',
      cloudSyncOn: 'Synchronizacja Chmury: Włączona',
      cloudSyncOff: 'Synchronizacja Chmury: Wyłączona',
      localStorage: 'Używanie Lokalnego Magazynu',
      noPreview: 'Podgląd niedostępny',
      runCode: 'Uruchom Kod',
      clearChat: 'Wyczyść Czat',
      exportChat: 'Eksportuj Czat',
      importChat: 'Importuj Czat',
      language: 'Język',
      theme: 'Motyw',
      dark: 'Ciemny',
      light: 'Jasny',
      auto: 'Automatyczny'
    }
  },
  nl: {
    code: 'nl',
    name: 'Dutch',
    nativeName: 'Nederlands',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'Welkom bij Codegent',
      guestMode: 'Gastmodus',
      signIn: 'Inloggen',
      signOut: 'Uitloggen',
      newProject: 'Nieuw Project',
      openProject: 'Project Openen',
      saveProject: 'Project Opslaan',
      deploy: 'Implementeren',
      deploying: 'Implementeren...',
      deploySuccess: 'Succesvol Geïmplementeerd!',
      deployError: 'Implementatie Mislukt',
      files: 'Bestanden',
      preview: 'Voorbeeld',
      chat: 'Chat',
      settings: 'Instellingen',
      models: 'Modellen',
      selectModel: 'Model Selecteren',
      compare: 'Modellen Vergelijken',
      regenerate: 'Regenereren',
      send: 'Verzenden',
      typeMessage: 'Typ je bericht...',
      thinking: 'Denken...',
      error: 'Fout',
      retry: 'Opnieuw',
      cancel: 'Annuleren',
      confirm: 'Bevestigen',
      delete: 'Verwijderen',
      rename: 'Hernoemen',
      newFile: 'Nieuw Bestand',
      newFolder: 'Nieuwe Map',
      loginRequired: 'Dit model vereist inloggen. Wilt u inloggen?',
      cloudSyncOn: 'Cloud Sync: Aan',
      cloudSyncOff: 'Cloud Sync: Uit',
      localStorage: 'Lokale Opslag Wordt Gebruikt',
      noPreview: 'Voorbeeld niet beschikbaar',
      runCode: 'Code Uitvoeren',
      clearChat: 'Chat Wissen',
      exportChat: 'Chat Exporteren',
      importChat: 'Chat Importeren',
      language: 'Taal',
      theme: 'Thema',
      dark: 'Donker',
      light: 'Licht',
      auto: 'Automatisch'
    }
  },
  sv: {
    code: 'sv',
    name: 'Swedish',
    nativeName: 'Svenska',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'Välkommen till Codegent',
      guestMode: 'Gästläge',
      signIn: 'Logga In',
      signOut: 'Logga Ut',
      newProject: 'Nytt Projekt',
      openProject: 'Öppna Projekt',
      saveProject: 'Spara Projekt',
      deploy: 'Distribuera',
      deploying: 'Distribuerar...',
      deploySuccess: 'Distribuerat Framgångsrikt!',
      deployError: 'Distribution Misslyckades',
      files: 'Filer',
      preview: 'Förhandsgranskning',
      chat: 'Chatt',
      settings: 'Inställningar',
      models: 'Modeller',
      selectModel: 'Välj Modell',
      compare: 'Jämför Modeller',
      regenerate: 'Regenerera',
      send: 'Skicka',
      typeMessage: 'Skriv ditt meddelande...',
      thinking: 'Tänker...',
      error: 'Fel',
      retry: 'Försök Igen',
      cancel: 'Avbryt',
      confirm: 'Bekräfta',
      delete: 'Radera',
      rename: 'Byt Namn',
      newFile: 'Ny Fil',
      newFolder: 'Ny Mapp',
      loginRequired: 'Denna modell kräver inloggning. Vill du logga in?',
      cloudSyncOn: 'Molnsynkronisering: På',
      cloudSyncOff: 'Molnsynkronisering: Av',
      localStorage: 'Använder Lokal Lagring',
      noPreview: 'Förhandsgranskning ej tillgänglig',
      runCode: 'Kör Kod',
      clearChat: 'Rensa Chatt',
      exportChat: 'Exportera Chatt',
      importChat: 'Importera Chatt',
      language: 'Språk',
      theme: 'Tema',
      dark: 'Mörk',
      light: 'Ljus',
      auto: 'Automatisk'
    }
  },
  uk: {
    code: 'uk',
    name: 'Ukrainian',
    nativeName: 'Українська',
    translations: {
      appTitle: 'Codegent AI Агент',
      welcome: 'Ласкаво просимо до Codegent',
      guestMode: 'Гостьовий Режим',
      signIn: 'Увійти',
      signOut: 'Вийти',
      newProject: 'Новий Проект',
      openProject: 'Відкрити Проект',
      saveProject: 'Зберегти Проект',
      deploy: 'Розгорнути',
      deploying: 'Розгортання...',
      deploySuccess: 'Успішно Розгорнуто!',
      deployError: 'Помилка Розгортання',
      files: 'Файли',
      preview: 'Попередній Перегляд',
      chat: 'Чат',
      settings: 'Налаштування',
      models: 'Моделі',
      selectModel: 'Вибрати Модель',
      compare: 'Порівняти Моделі',
      regenerate: 'Регенерувати',
      send: 'Надіслати',
      typeMessage: 'Введіть повідомлення...',
      thinking: 'Думаю...',
      error: 'Помилка',
      retry: 'Повторити',
      cancel: 'Скасувати',
      confirm: 'Підтвердити',
      delete: 'Видалити',
      rename: 'Перейменувати',
      newFile: 'Новий Файл',
      newFolder: 'Нова Папка',
      loginRequired: 'Ця модель потребує входу. Бажаєте увійти?',
      cloudSyncOn: 'Хмарна Синхронізація: Увімкнено',
      cloudSyncOff: 'Хмарна Синхронізація: Вимкнено',
      localStorage: 'Використовується Локальне Сховище',
      noPreview: 'Попередній перегляд недоступний',
      runCode: 'Запустити Код',
      clearChat: 'Очистити Чат',
      exportChat: 'Експорт Чату',
      importChat: 'Імпорт Чату',
      language: 'Мова',
      theme: 'Тема',
      dark: 'Темна',
      light: 'Світла',
      auto: 'Авто'
    }
  },
  vi: {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'Chào mừng đến Codegent',
      guestMode: 'Chế Độ Khách',
      signIn: 'Đăng Nhập',
      signOut: 'Đăng Xuất',
      newProject: 'Dự Án Mới',
      openProject: 'Mở Dự Án',
      saveProject: 'Lưu Dự Án',
      deploy: 'Triển Khai',
      deploying: 'Đang Triển Khai...',
      deploySuccess: 'Triển Khai Thành Công!',
      deployError: 'Triển Khai Thất Bại',
      files: 'Tệp',
      preview: 'Xem Trước',
      chat: 'Trò Chuyện',
      settings: 'Cài Đặt',
      models: 'Mô Hình',
      selectModel: 'Chọn Mô Hình',
      compare: 'So Sánh Mô Hình',
      regenerate: 'Tạo Lại',
      send: 'Gửi',
      typeMessage: 'Nhập tin nhắn...',
      thinking: 'Đang Suy Nghĩ...',
      error: 'Lỗi',
      retry: 'Thử Lại',
      cancel: 'Hủy',
      confirm: 'Xác Nhận',
      delete: 'Xóa',
      rename: 'Đổi Tên',
      newFile: 'Tệp Mới',
      newFolder: 'Thư Mục Mới',
      loginRequired: 'Mô hình này yêu cầu đăng nhập. Bạn có muốn đăng nhập không?',
      cloudSyncOn: 'Đồng Bộ Đám Mây: Bật',
      cloudSyncOff: 'Đồng Bộ Đám Mây: Tắt',
      localStorage: 'Đang Sử Dụng Bộ Nhớ Cục Bộ',
      noPreview: 'Không có xem trước',
      runCode: 'Chạy Mã',
      clearChat: 'Xóa Trò Chuyện',
      exportChat: 'Xuất Trò Chuyện',
      importChat: 'Nhập Trò Chuyện',
      language: 'Ngôn Ngữ',
      theme: 'Giao Diện',
      dark: 'Tối',
      light: 'Sáng',
      auto: 'Tự Động'
    }
  },
  th: {
    code: 'th',
    name: 'Thai',
    nativeName: 'ไทย',
    translations: {
      appTitle: 'Codegent AI Agent',
      welcome: 'ยินดีต้อนรับสู่ Codegent',
      guestMode: 'โหมดผู้เยี่ยมชม',
      signIn: 'เข้าสู่ระบบ',
      signOut: 'ออกจากระบบ',
      newProject: 'โปรเจคใหม่',
      openProject: 'เปิดโปรเจค',
      saveProject: 'บันทึกโปรเจค',
      deploy: 'ปรับใช้',
      deploying: 'กำลังปรับใช้...',
      deploySuccess: 'ปรับใช้สำเร็จ!',
      deployError: 'การปรับใช้ล้มเหลว',
      files: 'ไฟล์',
      preview: 'ดูตัวอย่าง',
      chat: 'แชท',
      settings: 'การตั้งค่า',
      models: 'โมเดล',
      selectModel: 'เลือกโมเดล',
      compare: 'เปรียบเทียบโมเดล',
      regenerate: 'สร้างใหม่',
      send: 'ส่ง',
      typeMessage: 'พิมพ์ข้อความของคุณ...',
      thinking: 'กำลังคิด...',
      error: 'ข้อผิดพลาด',
      retry: 'ลองอีกครั้ง',
      cancel: 'ยกเลิก',
      confirm: 'ยืนยัน',
      delete: 'ลบ',
      rename: 'เปลี่ยนชื่อ',
      newFile: 'ไฟล์ใหม่',
      newFolder: 'โฟลเดอร์ใหม่',
      loginRequired: 'โมเดลนี้ต้องเข้าสู่ระบบ คุณต้องการเข้าสู่ระบบหรือไม่?',
      cloudSyncOn: 'ซิงค์คลาวด์: เปิด',
      cloudSyncOff: 'ซิงค์คลาวด์: ปิด',
      localStorage: 'ใช้พื้นที่เก็บข้อมูลในเครื่อง',
      noPreview: 'ไม่มีตัวอย่าง',
      runCode: 'รันโค้ด',
      clearChat: 'ล้างแชท',
      exportChat: 'ส่งออกแชท',
      importChat: 'นำเข้าแชท',
      language: 'ภาษา',
      theme: 'ธีม',
      dark: 'มืด',
      light: 'สว่าง',
      auto: 'อัตโนมัติ'
    }
  }
};

// Language utility functions
const LanguageManager = {
  currentLanguage: 'en',
  
  init() {
    const savedLang = localStorage.getItem('codegent_language');
    if (savedLang && LANGUAGES[savedLang]) {
      this.currentLanguage = savedLang;
    } else {
      const browserLang = navigator.language.split('-')[0];
      if (LANGUAGES[browserLang]) {
        this.currentLanguage = browserLang;
      }
    }
    return this.currentLanguage;
  },
  
  setLanguage(langCode) {
    if (LANGUAGES[langCode]) {
      this.currentLanguage = langCode;
      localStorage.setItem('codegent_language', langCode);
      return true;
    }
    return false;
  },
  
  t(key) {
    const lang = LANGUAGES[this.currentLanguage] || LANGUAGES.en;
    return lang.translations[key] || LANGUAGES.en.translations[key] || key;
  },
  
  getLanguages() {
    return Object.entries(LANGUAGES).map(([code, lang]) => ({
      code,
      name: lang.name,
      nativeName: lang.nativeName
    }));
  },
  
  getCurrentLanguage() {
    return this.currentLanguage;
  }
};

// Export for module systems
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { LANGUAGES, LanguageManager };
}
